### ISSUE TITLE
No Release to install

### ISSUE THREAD

**Issue by oreillygshane** [Hau-Hau/firefox-tab-suspender#101]
Hi there,

Will releases be pushed via Github again, or will we need to compile?

Thanks!
Shane

**Comment by Hau-Hau** [comment]
Hello!

Sorry for that, I decided to freeze extension on mozilla's addon page until I will have new stable release.
I added latest release here: https://github.com/Hau-Hau/firefox-tab-suspender/releases/tag/3.7.4

Regards!
