### ISSUE TITLE
Can't find the addon on addons.mozilla.org anymore. Was it removed?

### ISSUE THREAD

**Issue by ProgrammingLife** [Hau-Hau/firefox-tab-suspender#102]
Can't find the addon on addons.mozilla.org anymore. Was it removed?

**Comment by Hau-Hau** [comment]
Hello, 

Because of criticism I decided to make addon private for a while, up to time when new release will be available.
I uploaded right now latest addons.mozilla.org release here: https://github.com/Hau-Hau/firefox-tab-suspender/releases/tag/3.7.4

Regards!
