### ISSUE TITLE
Disable automatic suspend on tabs with editable element.

### ISSUE THREAD

**Issue by zskdan** [Hau-Hau/firefox-tab-suspender#104]
As I enabled automatic suspending, when I switch a to new tab from a tab where I start editing a textarea or filling a form. the got suspended and the content is wipe out. 
 
Is there a way to disable the automatic suspend on tab containing a textarea/form or similar?

Thanks.

**Comment by Hau-Hau** [comment]
Hello, thanks for issue! I will close it because similar issue is opened already. You can get more information here: #53
