### ISSUE TITLE
Suspended Timer Increase

### ISSUE THREAD

**Issue by evanricard** [Hau-Hau/firefox-tab-suspender#11]
Hey Hau-Hau, is there any way to increase the amount of time it takes to suspend a tab? The 60 second rate is just too short for me. 

Thanks!

**Comment by Hau-Hau** [comment]
Hello!

You can change time in options (Firefox menu -> Add-ons -> Tab Suspender's preferences). After change remember to click blue 'save' button.

Best regards,
Michalewicz Piotr

**Comment by evanricard** [comment]
Does this let you change the time past 60 seconds? For some reason it’s not allowing that for me. Thanks.

Contact Info:
LinkedIn: https://www.linkedin.com/in/evanricard/
Github: https://github.com/evanricard
Portfolio: evanricard.com (Temporarily down, working on an alternative!)

**Comment by evanricard** [comment]
Never mind, worked just as you described, apologies!!

Contact Info:
LinkedIn: https://www.linkedin.com/in/evanricard/
Github: https://github.com/evanricard
Portfolio: evanricard.com (Temporarily down, working on an alternative!)
