### ISSUE TITLE
Clicking back results in the tab suspend page

### ISSUE THREAD

**Issue by camdenorrb** [Hau-Hau/firefox-tab-suspender#21]
After clicking to unsuspend a page, pressing the back button will result in going back to the suspension page.

**Comment by Hau-Hau** [comment]
Hello @camdenorrb, 

This issue is result of that non-native discarding is not finished yet - this problem will be gone in next versions also look of suspended page will be better (not only plain text on page).

Thanks for support!

**Comment by camdenorrb** [comment]
I might look into contributing down the line, what IDE do you personally use for this project?

**Comment by Hau-Hau** [comment]
@camdenorrb thanks for your support! Any help will be great because I don't have much time lately
Mostly for this project I use Visual Studio Code, but for bigger projects I prefer JetBrain's IDEs.

**Comment by Hau-Hau** [comment]
Done! Fix will come with next update!

And great thanks to man which send me e-mail with helpful tips!

Best regards!
