### ISSUE TITLE
Suspend option in context menu does not work

### ISSUE THREAD

**Issue by KirosC** [Hau-Hau/firefox-tab-suspender#25]
Hi,
I can't suspend a tab in the context menu but Suspend Others and Suspend All To The Left/Right are working fine.

**Comment by Hau-Hau** [comment]
Hello @KirosC!

You can suspend any tab that isn't the active one. Active tabs are ignored while suspending.

**Comment by KirosC** [comment]
Oh I see. I thought it is working like The Great Suspender.
