### ISSUE TITLE
Firefox randomly lost internet connection after a while

### ISSUE THREAD

**Issue by SNMetamorph** [Hau-Hau/firefox-tab-suspender#26]
I noticed problem, that when using this extension, after a while Firefox become unable to open/update web-pages, that visible as endless page loading.
Problem solves when I restart the browser, but problem may repeat after randomly period of time.
Also, I tried reinstall browser from scratch, but it its'n helped with this problem.
So, when I turned off suspender, problem stopped to happens.

Firefox version: 67.0.1 (64-bit)
Extension version: 3.4.4

**Comment by Hau-Hau** [comment]
Hello @SNMetamorph!

Are you use native or non-native discarding?

**Comment by SNMetamorph** [comment]
@Hau-Hau
Sorry, what do you mean by a discarding?

**Comment by Hau-Hau** [comment]
Thanks for reporting this issues guys. 

@SNMetamorph, I mean whether you have enabled or disabled option called "Non native discarding'.   

@mavyric, thanks, I have suspicious what can cause this problem.

At this month I have tons of work in job and at university so development is very slow. But around next month I should drop some updates.

Thanks for extension support!

**Comment by SNMetamorph** [comment]
So, I tested it with non-native discarding and without, but this problem occur anyway.

**Comment by Hau-Hau** [comment]
@SNMetamorph, thanks. It is important because I was thinking that this bug occur only when option is enabled.

**Comment by Hau-Hau** [comment]
Hello guys!

i was released new version of extension (3.4.6)
On new version I don't have any problems that you mentioned.

It will be helpful if you guys told me whether you have still problems.

Best regards,
Michalewicz Piotr

**Comment by SNMetamorph** [comment]
Ok, I'll try it and report if something goes wrong.
