### ISSUE TITLE
Feature request: Restore discarded page after refreshing (F5)

### ISSUE THREAD

**Issue by Chst8754** [Hau-Hau/firefox-tab-suspender#29]
Refreshing a discarded site reloads the discarded version. It would be much nicer to have the original version of the site (the non-discarded one) show up instead.

**Comment by Hau-Hau** [comment]
Hi @Chst8754, I was thinking about this feature. I think it will be nice - it works well in _The Great Suspender_. I will add this feature to task list on trello.
But please be patient, there is ton of works with bugs, tests and other things so I'm not sure when I will add this feature.

Thanks for feature requests!
Best regards!

**Comment by Hau-Hau** [comment]
Done.
https://github.com/Hau-Hau/firefox-tab-suspender/pull/38#issue-314206065
