### ISSUE TITLE
The current tab is not manually frozen.

### ISSUE THREAD

**Issue by Hifexar** [Hau-Hau/firefox-tab-suspender#30]
The current tab is not manually frozen.

If you try to freeze the current tab through the context menu, nothing happens.

https://gyazo.com/7468cc7ae45d319d81d689a5f409aee8

Feature request:
1. Please add to the context menu on the page itself, as in the great tab suspender.
2. Please add hotkeys for manual freezing of tab, as in the great tab suspender.

Working in automatic mode is not interesting. Interesting manual work. Freeze temporarily unnecessary tabs, not so much to reduce memory usage as to stop network activity.

**Comment by Hau-Hau** [comment]
Hello! 

_You can suspend any tab that isn't the active one. Active tabs are ignored while suspending._

Check this issue https://github.com/Hau-Hau/firefox-tab-suspender/issues/25

**Comment by Hifexar** [comment]
Can we make it not to be ignored? Because usually need to freeze it active.

**Comment by Hau-Hau** [comment]
It is possible, but this is not way of that how system works now.
There will be needed some changes in code (it is not feature that can be finished in 30 sec.).

I  will reopen issue, we will check what thinks about that other people.

**Comment by Hau-Hau** [comment]
Hello!

In new version (3.6.0) is it possible to suspend currently selected tab!

Best regards,
Michalewicz Piotr
