### ISSUE TITLE
[Feature Request] Ability to pause background processes of tabs.

### ISSUE THREAD

**Issue by LichenSymbiont** [Hau-Hau/firefox-tab-suspender#32]
Pausing all tabs but tabs playing media, and the presently active tab.

I've sent a feature request to Bugzilla, bugzilla.mozilla.org/show_bug.cgi?id=1545701, but to implement it in an extension first would be best. And this is already a promising addon.

If more people were aware of the background activity of tabs that really shouldn't be doing anything in the background by keeping an eye on the task manager (about:performance), I think there'd be a multitude of people requesting a more desirable silence when you're not doing stuff in the browser.

**Comment by Hau-Hau** [comment]
I don't understand your post in some parts, but from that what I understand and from that bugzilla site i read, you want to pause background processes that are on sites instead of discarding tabs. I understand that correctly?

If I understand you correctly, I think this feature will be very complicated and it can be material for another standalone extension.

**Comment by LichenSymbiont** [comment]
Yes, I was afraid of that. But I had to check, because as I'm now more aware of the issue, with the HDD waking up from the background processes of tabs in the browser. And seeing the constant activity in the task manager in Linux and in Firefox.

I guess I will have to look into it myself, and ask around.

But this addon is the best we've got to save ram and shut down the background processes. Just needs to resume the tabs like when you activate an inactive tab like usual. No extra clicking.

**Comment by Hau-Hau** [comment]
In future version is planned to make automatic activating and scrolling to last position on site. This is not what you want in 100%, but it will be closer.

Beside of that, feature that you mentioned in my opinion is very complicated, I not even sure whether this is possible through Firefox api. 

If you will get any informations about that, share them with us!

**Comment by LichenSymbiont** [comment]
Yes, I will definitely! I'm on a quest for a silent Firefox. And the best result would be if it could be shared with everyone by patching Firefox. But there's things you might want to have running in the background that's not media, so an official solution seems unlikely. As they want to keep things as simple as possible.

But if there are scripts that you need to run a site, that may compromise security, then the argument is stronger. And there are... such sites wouldn't be recommended by security experts, but people will do all kinds of things to compromise their security.
To not run scripts when not needed is a good extra precaution.

I've posted feature requests for it for NoScript and uMatrix as well, so we'll have to wait and see. I will try to find the relevant parts in the Firefox code next. As it would be good to have a run/stop/pause API for scripts. And to be able to monitor CPU and RAM usage, so that addons like this can shut down tabs with little CPU usage (just background noise, and probably not doing anything useful for the user), and RAM usage, so you can prioritize what tabs to shut down first, together with other factors.

**Comment by Hau-Hau** [comment]
I found still experimental extension to Chromium based browsers. 
Maybe it will be interesting for you.

https://github.com/usnistgov/Metrology/tree/master/Reaper
