### ISSUE TITLE
Do not focus tab on suspension

### ISSUE THREAD

**Issue by kirkmadera** [Hau-Hau/firefox-tab-suspender#33]
I keep getting sent to a tab as it has been suspended. There is no reason I would ever want to look at a tab that was just suspended. Is this intended behavior? Does this happen to anyone else?

**Comment by Hau-Hau** [comment]
Hello!

This is very strange behaviour.
Whether tab to which you has been sent had open developer console?
Today I was released new version of extension, pleases check whether you still have this problem.

Best regards,
Michalewicz Piotr
