### ISSUE TITLE
Suspending music.youtube.com tab

### ISSUE THREAD

**Issue by slava-basko** [Hau-Hau/firefox-tab-suspender#35]
Preferences: http://img.ringostat.com/slav/1565600059368.png.
Icon on tab http://img.ringostat.com/slav/1565600158771.png. As i understand Firefox(68.0.1 on macOS 10.14.5) knows that this tab playing audio. But extension still suspend this tab.

**Comment by Hau-Hau** [comment]
Hello!

Thanks for bug report, I will investigate this problem.

Best regards,
Michalewicz Piotr

**Comment by 0trenixjetix** [comment]
Hi, i have this problem also.
I got the last version but still suspends.

**Comment by slava-basko** [comment]
Sorry for late response. Current version 3.5.0

**Comment by Hau-Hau** [comment]
Hello,

It is weird for me because often I'm listening music from YouTube and i don't have any problem like that.
I think it can be related with bug that I fixed yesterday.
I released yesterday new version 3.5.1. 
Please check whether you still have problems.

Best regards,
Michalewicz Piotr

**Comment by 0trenixjetix** [comment]
I still got problems with some tabs like twitch.tv that suspend even if sound is playing.
