### ISSUE TITLE
Suspend delay not being kept

### ISSUE THREAD

**Issue by Ssurgul** [Hau-Hau/firefox-tab-suspender#37]
I've been trying to set a time delay larger than 60 seconds (default), but every time I do, the system loses the change and returns to 60 seconds. I've tried with various times from 5 to 20 minutes.

Running FFQ 68.0.2

**Comment by Hau-Hau** [comment]
Hello, @Ssurgul! 

Do you click blue 'save' button?

Best regards,
Michalewicz Piotr

**Comment by Hau-Hau** [comment]
Fixed.
After update everything should be fine.
https://github.com/Hau-Hau/firefox-tab-suspender/pull/38#issue-314206065
