### ISSUE TITLE
First tab is not suspending

### ISSUE THREAD

**Issue by mcbbcn** [Hau-Hau/firefox-tab-suspender#41]
I open all tabs and they all go into suspension but the first one, even when it's not active.

Work around: Close the first tab you open (i.e. Gmail) and open more new tab (i.e. Gmail) and because now, it's not the first tab, it seems to suspend it just fine.

**Comment by Hau-Hau** [comment]
Hello @mcbbcn,

Today I released new version (3.5.1).
Please check whether you still have problems in new version.

Best regards,
Michalewicz Piotr

**Comment by Hau-Hau** [comment]
Hello!

Today I released new version (3.6.0).
This bug should't appear in new version.

Best regards,
Michalewicz Piotr
