### ISSUE TITLE
Suspender ignores the "suspend tab after (seconds)"

### ISSUE THREAD

**Issue by ITgreybeard** [Hau-Hau/firefox-tab-suspender#42]
I have saved the value '900' to "suspend tab after (seconds)" but the tab is suspended after 60 seconds. So it appears that the value is disregarded.

**Comment by Hau-Hau** [comment]
Hello @ITgreybeard,

Today I released new version (3.5.1). 
Please check whether you still have problems in new version.

Best regards,
Michalewicz Piotr

**Comment by khawajamechatronics** [comment]
Hi 
I am using version 3.5.2 and having same issue, its suspending tabs very quickly. Even If I switch tab for 5 secs came back to last tab and I see its suspended.

**Comment by SNMetamorph** [comment]
+, having same issue on last version

**Comment by Hau-Hau** [comment]
Thanks guys for report.
I'm starting debugging.

**Comment by khawajamechatronics** [comment]
1- After first issue, it repeatedly occurs
2- After Sometime of browsing, may be after first suspend hit
3- I have multiple windows open.

**Comment by 0trenixjetix** [comment]
I got still this problem when i switch tab from twitch.tv (When it has sound.)

**Comment by Hau-Hau** [comment]
@khawajamechatronics,
Thanks!

@0trenixjetix,
Thanks for report.
I found possible gap - it is possible to suspend tab which is playing audio when e.g. video on youtube is changing. I will fix that. 
Issue related to problems with audio you can track here: #35

Best regards,
Michalewicz Piotr

**Comment by whalemonster** [comment]
I also have this issue on the latest version. I have set the delay to 300s but the add-on ignores this and suspends tabs more quickly. This happens on all tabs, regardless of content.

**Comment by notacompletemoron** [comment]
I am having this issue, along with another which I will open a new ticket for.

**Comment by Hau-Hau** [comment]
Hello,

I rewrited a lot parts of C code (including event loop), this bug should't be a problem anymore.
Do you guys still have this problems in newest version (3.6.0+)?

Best regards,
Michalewicz Piotr

**Comment by khawajamechatronics** [comment]
I am using 3.7.4 and I think its much better now.
