### ISSUE TITLE
after some inactivity, tabs cant be loaded anymore, at all

### ISSUE THREAD

**Issue by toppits** [Hau-Hau/firefox-tab-suspender#46]
as the title says. I have to restart the browser completely to load anything again

Started a few months ago probably after some FF update as it worked fine before.

**Comment by Hau-Hau** [comment]
Hello @toppits,

Today I shipped new version (3.5.2).
Do you still have problems on new version?
Please be sure about that which version do you use.
I'm will be waiting for feedback.

Best regards,
Michalewicz Piotr

**Comment by toppits** [comment]
yes, its on auto update. 

But i just remember, back when i disabled it, i did change the 'seconds' value to 150. Now sure what the time frame between that and the occurring issue was, but its the only thing i can think of that was in my control (no other add-ons etc). 

I've now reset it to default 60 and see how that goes

**Comment by Hau-Hau** [comment]
Hello,

Please check if you still have this problem in newest version (3.6.0+).

Best regards,
Michalewicz Piotr
