### ISSUE TITLE
Tabs gets suspended even after activity

### ISSUE THREAD

**Issue by kamilmirza** [Hau-Hau/firefox-tab-suspender#47]
as per title
tabs are getting suspended after switching switching through them or after activity
looks like Tab Suspender is following "Automatically suspend tabs after x seconds" without any trigger
the "Automatically suspend tabs after x seconds" feature trigger should **reset** after any activity on the tab

v 3.5.2
Firefox 70.0.1
win10 x64

**Comment by Hau-Hau** [comment]
Hello,

In version 3.5.2 there was many bugs that I fixed in 3.6.0.
Also automatic suspending under the hood works differently in newest version.  

Please check if you still have this problem in newest version (3.6.0+).

Best regards,
Michalewicz Piotr
