### ISSUE TITLE
Suspend Active Tab in Context Menu

### ISSUE THREAD

**Issue by DarkYuan** [Hau-Hau/firefox-tab-suspender#48]
Something that I used a lot in The Great Suspender that I wish I could use here is being able to suspend the current tab, usually through the context menu on the page itself, not on the tab's context menu.

**Comment by madduck** [comment]
See #55, #41, #30

**Comment by Hau-Hau** [comment]
Hello! 

New version (3.6.0) is out!
Now it is possible to suspend a active one tab!

Best regards,
Michalewicz Piotr
