### ISSUE TITLE
Ignores playing audio and time to suspend

### ISSUE THREAD

**Issue by notacompletemoron** [Hau-Hau/firefox-tab-suspender#54]
Firefox 71.0 and Tab Suspender 3.5.2

I frequently watch Factorio streams on Twitch, and the broadcasters usually go quiet long enough for the tab to register no sound. If I am in another tab, and the sound doesn't always go away, the tab gets suspended immediately.

It's ignoring the 300 second timeout, on top of ignoring audio output.

**Comment by Hau-Hau** [comment]
Hello! Currently I'm working on bug fixes.
