### ISSUE TITLE
Suspend Current Tab Not Working

### ISSUE THREAD

**Issue by DominusMaximus** [Hau-Hau/firefox-tab-suspender#55]
When I right click on the active tab and choose "Suspend", nothing happens. All of the other suspend commands work. Right clicking that tab and choosing "Suspend" _while in another_ tab works though.

**Comment by Mulsiphix** [comment]
Confirming that this is happening for me as well.

Firefox v71.0 (64-bit)

**Comment by ideaman924** [comment]
Same problem here, Firefox v71.0, macOS 10.15.2

**Comment by DominusMaximus** [comment]
Something I hadn't realized

**Comment by chamini2** [comment]
Duplicate of #30

**Comment by Hau-Hau** [comment]
Hello all!

New version is coming into _Firefox Browser Add-Ons_
In new version is it possible to suspend currently selected tab!

Best regards,
Michalewicz Piotr
