### ISSUE TITLE
stealing data?

### ISSUE THREAD

**Issue by aung-san-i** [Hau-Hau/firefox-tab-suspender#56]
Why this extension needs this permission "Access your data for all websites" ???

**Comment by Hau-Hau** [comment]
Hello!

No, I'm not stealing any data! :)
Code is open source, you can be sure that I'm not interested in any data gathering.
More about this topic you can read under this link: #1 

Best regards,
Michalewicz Piotr

**Comment by aung-san-i** [comment]
Please accept my apology. It was Firefox confusion. I will open issue with FireFox. Thanks lots for reply and info.

**Comment by Hau-Hau** [comment]
No problem!
It is great to see people that are interested in their privacy!

Best regards,
Michalewicz Piotr
