### ISSUE TITLE
Key to suspend current tab

### ISSUE THREAD

**Issue by madduck** [Hau-Hau/firefox-tab-suspender#57]
Assuming that the current tab will become suspendable at some point (#55, #48, #41, #30), it would be great to be able to have a key shortcut for it too, like e.g. `F8` to suspend the current tab.

**Comment by Hau-Hau** [comment]
Hello @madduck!

This feature is on roadmap!
Latest weeks I had no time to work on extension. 
Now I will continue development, but first there is some critical bugs to fix. 
When extension will be works without critical issues I will be doing less important tasks.

Best regards,
Michalewicz Piotr
