### ISSUE TITLE
suspension of the allready suspended tab

### ISSUE THREAD

**Issue by BraunLukas** [Hau-Hau/firefox-tab-suspender#63]
Review from firefox:
> suspends same tab multiple times and is afterwards not able to restore the tab as it was...
> Had to urldecode several times to at least reget the url that i had opened... (for 30 tabs..)

the plugin suspended an allready suspended tab: urldecoded the "suspend:url" 

with two "suspendings" its still working as the click on the site encodes the url to the original suspended-url and on second click, it opens the right url

With more "recursive suspendings" it only shows a white page or a page with "click to restore". On click nothing happens.

Sorry i cant provide you the double and triple encoded urls, but i'm not going to reinstall the plugin. sry ;)

Version 3.6.4
Firefox 72.0.1 (Firefox for Ubuntu canonical -1.0)
Ubuntu 18.04

**Comment by Hau-Hau** [comment]
Thanks for reporting issue and sorry for any problems that you had with extension.

I'm using extension daily and I don't had this issue but there for sure is something wrong with automatic suspending.

Please check extension again when will be out from experimental phase!

Best regards,
Michalewicz Piotr

**Comment by BraunLukas** [comment]
Sure
 hope you find the bug causing this problem

________________________________
Von: Michalewicz Piotr <notifications@github.com>
Gesendet: Samstag, 18. Januar 2020 00:21
An: Hau-Hau/firefox-tab-suspender
Cc: Braun Lukas; Author
Betreff: Re: [Hau-Hau/firefox-tab-suspender] suspension of the allready suspended tab (#63)


Thanks for reporting issue and sorry for any problems that you had with extension.

I'm using extension daily and I don't had this issue but there for sure is something wrong with automatic suspending.

Please check extension again when will be out from experimental phase!

Best regards,
Michalewicz Piotr

**Comment by Hau-Hau** [comment]
New version has completely rewritted background JavaScript - issue should't by a problem anymore.
If no more one report similar bug I will close issue in near future.
