### ISSUE TITLE
Visible tabs on hidden/unfocused windows not suspending. 

### ISSUE THREAD

**Issue by Racer-X-9** [Hau-Hau/firefox-tab-suspender#72]
I consider this a bug, although you might consider it a feature request. 

I have my tab-suspender plugin set to automatically suspend tabs after 300 seconds.  I also have pinned tabs set to not suspend. 

The issue is, some tabs never suspend.  The visible tab on every window never suspends. Sometimes I open multiple windows, and I might have 6 or 8 (or a dozen windows open). Some are on other workspaces I'm not looking at.  Others are hidden or partially hidden behind the window I'm reading or looking at. 

I'd at least like the option to tell it, "Suspend visible tabs on unfocused windows."  This action would be negated if the visible tab is pinned and the "Never suspend pinned tabs" is checked. 

It would also be very handy to suspend the visible tab immediately on a minimized window. That should happen, **except** if that visible tab is pinned and "Never suspend pinned tabs" is checked.

**Comment by Hau-Hau** [comment]
Hello,

Active tabs are not suspending, this is not bug. Tab suspender is not checking whether tab is visible from user perspective point of view.

In my opinion your idea is very nice, I will add your features proposition to task list.

Best regards!
