### ISSUE TITLE
Local images do not resume 

### ISSUE THREAD

**Issue by ochompsky** [Hau-Hau/firefox-tab-suspender#83]
I'm on OSX.  If I have an image on my computer opened in Chrome, for example the URL would be `file:///Users/user/Desktop/IMG_2345.jpg`, it will not open when I try to 'unsuspend' the tab.  Have not tried for other files but it could apply to all local files, HTML as well.

**Comment by Hau-Hau** [comment]
Hello @ochompsky, thanks for bug report!

It is known bug, currently I'm working on big changes in codebase so it take some time until I release new version. 
There is another thread about this bug so I will close this issue: #75 

Best regards,
Michalewicz Piotr
