### ISSUE TITLE
Immediately restore tab?

### ISSUE THREAD

**Issue by neo-neo1** [Hau-Hau/firefox-tab-suspender#90]
What exactly does the option "Immediately restore tab" supposed to achieve? Can anyone share, is there a con to enabling it? 

I found no respective GitHub Wiki, nothing on the main GitHub page, nor anything useful on the Firefox Extension page. Thus, this is my last resort. What exactly is the purpose of said option?

**Comment by Hau-Hau** [comment]
Hello, if immediately restore tab option is enabled then page have to be restored to normal mode on tab activation (without needed to click on page or refreshing).
