### ISSUE TITLE
Feature Request: Do not suspend "data:" URLs

### ISSUE THREAD

**Issue by mozai** [Hau-Hau/firefox-tab-suspender#92]
tabs viewing "data:" urls are rarely (almost never) resource heavy.  Tab Suspender is unable to restore them.

If someone's bothered to use a "data:" url, it's likely one static blob of media, or an ephemeral page, neither needs suspending.

**Comment by Hau-Hau** [comment]
Hello, thanks for issue. I'm closing because there is thread about very similar problem. (#75)
