### ISSUE TITLE
[Feature Suggestion] Youtube position suspend

### ISSUE THREAD

**Issue by friendlytherapist** [Hau-Hau/firefox-tab-suspender#99]
Is it possible to add remembering the youtube position when suspending and unsuspending a youtube tab? You could perhaps use the &t=seconds addition to the youtube url or something else.

**Comment by Hau-Hau** [comment]
Hello!

I think it will be available in next stable release.
I'm closing thin issue because there already exists topic about same thing. (#51)

Regards!
